export const VALIDATION_ERROR_CODES = {
  NOT_A_STRING: 'NOT_A_STRING',
  IS_EMPTY: 'IS_EMPTY',
  INVALID_ENUM_VALUE: 'INVALID_ENUM_VALUE',
  NOT_A_NUMBER: 'NOT_A_NUMBER',
  NOT_A_DATE: 'NOT_A_DATE',
  NOT_AN_EMAIL: 'NOT_AN_EMAIL',
  NOT_MINIMUM_AGE: 'NOT_MINIMUM_AGE',
  TOO_SHORT: 'TOO_SHORT',
  TOO_LONG: 'TOO_LONG',
  INVALID_FORMAT: 'INVALID_FORMAT', // used for password (also for date), returns the whole regex mismatch error in one message
  INVALID_TOKEN: 'INVALID_TOKEN',
  MISSING_HEADER: 'MISSING_HEADER',
  INVALID_VALUE: 'INVALID_VALUE',
  INVALID_PARAM: 'INVALID_PARAM',
  INVALID_COUNTRY: 'INVALID_COUNTRY',
  INVALID_GENDER: 'INVALID_GENDER',
  INVALID_LANGUAGE: 'INVALID_LANGUAGE',
};

export const CONSTRAINT_TO_ERROR_CODE_MAP: Record<string, string> = {
  // Type validators
  isString: VALIDATION_ERROR_CODES.NOT_A_STRING,
  isNumber: VALIDATION_ERROR_CODES.NOT_A_NUMBER,
  isDate: VALIDATION_ERROR_CODES.NOT_A_DATE,

  // Common validators
  isNotEmpty: VALIDATION_ERROR_CODES.IS_EMPTY,
  isEmail: VALIDATION_ERROR_CODES.NOT_AN_EMAIL,
  isEnum: VALIDATION_ERROR_CODES.INVALID_ENUM_VALUE,
  isEmpty: VALIDATION_ERROR_CODES.IS_EMPTY,

  // String length validators
  minLength: VALIDATION_ERROR_CODES.TOO_SHORT,
  maxLength: VALIDATION_ERROR_CODES.TOO_LONG,

  // Custom password validators (if you're using @Matches() with patterns)
  matches: VALIDATION_ERROR_CODES.INVALID_FORMAT,

  // custom validators
  isMinYearsOld: VALIDATION_ERROR_CODES.NOT_MINIMUM_AGE,
  invalidToken: VALIDATION_ERROR_CODES.INVALID_TOKEN,
  missingHeader: VALIDATION_ERROR_CODES.MISSING_HEADER,
  invalidValue: VALIDATION_ERROR_CODES.INVALID_VALUE,
  isOptionalDate: VALIDATION_ERROR_CODES.NOT_A_DATE,
  invalidParam: VALIDATION_ERROR_CODES.INVALID_PARAM,

  invalidCountry: VALIDATION_ERROR_CODES.INVALID_COUNTRY,
  invalidGender: VALIDATION_ERROR_CODES.INVALID_GENDER,
  invalidLanguage: VALIDATION_ERROR_CODES.INVALID_LANGUAGE,
};
