export const CONVERSATIONS_ERROR_CODES = {
  BLOCKED_USER: 'BLOCKED_USER',
  CONVERSATION_CREATION_FAILED: 'CONVERSATION_CREATION_FAILED',
  INVALID_CONVERSATION_ID: 'INVALID_CONVERSATION_ID',
  FORBIDDEN_CONVERSATION_ID: 'FORBIDDEN_CONVERSATION_ID',
} as const;

export const CONVERSATIONS_ERROR_MESSAGES = {
  CONVERSATION_CREATION_FAILED: 'Failed to create conversation',
  INVALID_CONVERSATION_ID: 'Failed to get this conversation',
  FORBIDDEN_CONVERSATION_ID: "You can't access this conversation",
} as const;
