export const NOTIFICATIONS_ERROR_CODES = {
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
};

export const NOTIFICATIONS_ERROR_MESSAGES = {
  NOTIFICATION_NOT_FOUND: 'Notification not found.',
};
